spring.application.name=utility-service
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=byebye.application@gmail.com
spring.mail.password=zmdctzsvsapzughi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
