services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ByeBye
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-service:
    image: vanessa19/app-service:latest
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ByeBye?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      UTILITY_SERVICE_URL: http://utility-service:8080
    depends_on:
      mysql:
        condition: service_healthy

  utility-service:
    image: vanessa19/utility-service:latest
    ports:
      - "8080:8080"
    depends_on:
       mysql:
        condition: service_healthy