spring.application.name=backend

# LOGS 
logging.level.org.springframework.web=DEBUG
spring.mustache.suffix=.html

# ========================
# BASE DE DATOS
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/ByeBye?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ========================
# SERVIDOR
# ========================
server.port=8443
spring.web.error.whitelabel.enabled=false

# =====================
# CORREO
# =====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=byebye.application@gmail.com
spring.mail.password=zmdctzsvsapzughi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true