spring.application.name=backend
spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
logging.level.org.springframework.web=DEBUG
spring.mustache.suffix=.html
